language: ruby
script: bundle exec rake spec:$SUITE
rvm:
  # - rbx-19mode
  - ruby-2.1.3
notifications:
  email:
    recipients:
      - drnicwilliams@gmail.com
    on_success: change
    on_failure: always
env:
  matrix:
    - SUITE=unit
    - SUITE=integration
  global:
    - secure: ""
